name: Ruff Checks

on:
  pull_request:
    branches:
      - "**" # Run on all branches for pull requests

jobs:
  ruff_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff check (I violations)
        run: ruff check . --select I

      - name: Run Ruff formatting check
        run: ruff format --check

      - name: Run full Ruff check
        run: ruff check .
